// Code generated by MockGen. DO NOT EDIT.
// Source: cheapskate/internal/reconcile (interfaces: Notifier,SnsAPI)
//
// Generated by this command:
//
//	mockgen -destination ../mocks/reconcile.go -package mocks cheapskate/internal/reconcile Notifier,SnsAPI
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sns "github.com/aws/aws-sdk-go-v2/service/sns"
	gomock "go.uber.org/mock/gomock"
)

// MockNotifier is a mock of Notifier interface.
type MockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierMockRecorder
	isgomock struct{}
}

// MockNotifierMockRecorder is the mock recorder for MockNotifier.
type MockNotifierMockRecorder struct {
	mock *MockNotifier
}

// NewMockNotifier creates a new mock instance.
func NewMockNotifier(ctrl *gomock.Controller) *MockNotifier {
	mock := &MockNotifier{ctrl: ctrl}
	mock.recorder = &MockNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifier) EXPECT() *MockNotifierMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockNotifier) Publish(ctx context.Context, subject string, payload map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, subject, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockNotifierMockRecorder) Publish(ctx, subject, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockNotifier)(nil).Publish), ctx, subject, payload)
}

// MockSnsAPI is a mock of SnsAPI interface.
type MockSnsAPI struct {
	ctrl     *gomock.Controller
	recorder *MockSnsAPIMockRecorder
	isgomock struct{}
}

// MockSnsAPIMockRecorder is the mock recorder for MockSnsAPI.
type MockSnsAPIMockRecorder struct {
	mock *MockSnsAPI
}

// NewMockSnsAPI creates a new mock instance.
func NewMockSnsAPI(ctrl *gomock.Controller) *MockSnsAPI {
	mock := &MockSnsAPI{ctrl: ctrl}
	mock.recorder = &MockSnsAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSnsAPI) EXPECT() *MockSnsAPIMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockSnsAPI) Publish(ctx context.Context, in *sns.PublishInput, opts ...func(*sns.Options)) (*sns.PublishOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Publish", varargs...)
	ret0, _ := ret[0].(*sns.PublishOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockSnsAPIMockRecorder) Publish(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockSnsAPI)(nil).Publish), varargs...)
}
