// Code generated by MockGen. DO NOT EDIT.
// Source: cheapskate/internal/target (interfaces: Target,RdsAPI,EcsAPI,AutoScalingAPI)
//
// Generated by this command:
//
//	mockgen -destination ../mocks/target.go -package mocks cheapskate/internal/target Target,RdsAPI,EcsAPI,AutoScalingAPI
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "cheapskate/internal/model"
	context "context"
	reflect "reflect"

	applicationautoscaling "github.com/aws/aws-sdk-go-v2/service/applicationautoscaling"
	ecs "github.com/aws/aws-sdk-go-v2/service/ecs"
	rds "github.com/aws/aws-sdk-go-v2/service/rds"
	gomock "go.uber.org/mock/gomock"
)

// MockTarget is a mock of Target interface.
type MockTarget struct {
	ctrl     *gomock.Controller
	recorder *MockTargetMockRecorder
	isgomock struct{}
}

// MockTargetMockRecorder is the mock recorder for MockTarget.
type MockTargetMockRecorder struct {
	mock *MockTarget
}

// NewMockTarget creates a new mock instance.
func NewMockTarget(ctrl *gomock.Controller) *MockTarget {
	mock := &MockTarget{ctrl: ctrl}
	mock.recorder = &MockTargetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTarget) EXPECT() *MockTargetMockRecorder {
	return m.recorder
}

// Describe mocks base method.
func (m *MockTarget) Describe(ctx context.Context, ref string) (model.Observation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Describe", ctx, ref)
	ret0, _ := ret[0].(model.Observation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Describe indicates an expected call of Describe.
func (mr *MockTargetMockRecorder) Describe(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Describe", reflect.TypeOf((*MockTarget)(nil).Describe), ctx, ref)
}

// PrepareStop mocks base method.
func (m *MockTarget) PrepareStop(ctx context.Context, ref string, cfg model.Config, status model.Status) (*model.SavedState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareStop", ctx, ref, cfg, status)
	ret0, _ := ret[0].(*model.SavedState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareStop indicates an expected call of PrepareStop.
func (mr *MockTargetMockRecorder) PrepareStop(ctx, ref, cfg, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareStop", reflect.TypeOf((*MockTarget)(nil).PrepareStop), ctx, ref, cfg, status)
}

// Start mocks base method.
func (m *MockTarget) Start(ctx context.Context, ref string, cfg model.Config, status model.Status) (*model.SavedState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, ref, cfg, status)
	ret0, _ := ret[0].(*model.SavedState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockTargetMockRecorder) Start(ctx, ref, cfg, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockTarget)(nil).Start), ctx, ref, cfg, status)
}

// Stop mocks base method.
func (m *MockTarget) Stop(ctx context.Context, ref string, cfg model.Config, status model.Status) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx, ref, cfg, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockTargetMockRecorder) Stop(ctx, ref, cfg, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockTarget)(nil).Stop), ctx, ref, cfg, status)
}

// Type mocks base method.
func (m *MockTarget) Type() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(string)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockTargetMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockTarget)(nil).Type))
}

// MockRdsAPI is a mock of RdsAPI interface.
type MockRdsAPI struct {
	ctrl     *gomock.Controller
	recorder *MockRdsAPIMockRecorder
	isgomock struct{}
}

// MockRdsAPIMockRecorder is the mock recorder for MockRdsAPI.
type MockRdsAPIMockRecorder struct {
	mock *MockRdsAPI
}

// NewMockRdsAPI creates a new mock instance.
func NewMockRdsAPI(ctrl *gomock.Controller) *MockRdsAPI {
	mock := &MockRdsAPI{ctrl: ctrl}
	mock.recorder = &MockRdsAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRdsAPI) EXPECT() *MockRdsAPIMockRecorder {
	return m.recorder
}

// DescribeDBClusters mocks base method.
func (m *MockRdsAPI) DescribeDBClusters(ctx context.Context, in *rds.DescribeDBClustersInput, opts ...func(*rds.Options)) (*rds.DescribeDBClustersOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeDBClusters", varargs...)
	ret0, _ := ret[0].(*rds.DescribeDBClustersOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeDBClusters indicates an expected call of DescribeDBClusters.
func (mr *MockRdsAPIMockRecorder) DescribeDBClusters(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeDBClusters", reflect.TypeOf((*MockRdsAPI)(nil).DescribeDBClusters), varargs...)
}

// DescribeDBInstances mocks base method.
func (m *MockRdsAPI) DescribeDBInstances(ctx context.Context, in *rds.DescribeDBInstancesInput, opts ...func(*rds.Options)) (*rds.DescribeDBInstancesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeDBInstances", varargs...)
	ret0, _ := ret[0].(*rds.DescribeDBInstancesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeDBInstances indicates an expected call of DescribeDBInstances.
func (mr *MockRdsAPIMockRecorder) DescribeDBInstances(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeDBInstances", reflect.TypeOf((*MockRdsAPI)(nil).DescribeDBInstances), varargs...)
}

// StartDBCluster mocks base method.
func (m *MockRdsAPI) StartDBCluster(ctx context.Context, in *rds.StartDBClusterInput, opts ...func(*rds.Options)) (*rds.StartDBClusterOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StartDBCluster", varargs...)
	ret0, _ := ret[0].(*rds.StartDBClusterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartDBCluster indicates an expected call of StartDBCluster.
func (mr *MockRdsAPIMockRecorder) StartDBCluster(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartDBCluster", reflect.TypeOf((*MockRdsAPI)(nil).StartDBCluster), varargs...)
}

// StartDBInstance mocks base method.
func (m *MockRdsAPI) StartDBInstance(ctx context.Context, in *rds.StartDBInstanceInput, opts ...func(*rds.Options)) (*rds.StartDBInstanceOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StartDBInstance", varargs...)
	ret0, _ := ret[0].(*rds.StartDBInstanceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartDBInstance indicates an expected call of StartDBInstance.
func (mr *MockRdsAPIMockRecorder) StartDBInstance(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartDBInstance", reflect.TypeOf((*MockRdsAPI)(nil).StartDBInstance), varargs...)
}

// StopDBCluster mocks base method.
func (m *MockRdsAPI) StopDBCluster(ctx context.Context, in *rds.StopDBClusterInput, opts ...func(*rds.Options)) (*rds.StopDBClusterOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StopDBCluster", varargs...)
	ret0, _ := ret[0].(*rds.StopDBClusterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StopDBCluster indicates an expected call of StopDBCluster.
func (mr *MockRdsAPIMockRecorder) StopDBCluster(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopDBCluster", reflect.TypeOf((*MockRdsAPI)(nil).StopDBCluster), varargs...)
}

// StopDBInstance mocks base method.
func (m *MockRdsAPI) StopDBInstance(ctx context.Context, in *rds.StopDBInstanceInput, opts ...func(*rds.Options)) (*rds.StopDBInstanceOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StopDBInstance", varargs...)
	ret0, _ := ret[0].(*rds.StopDBInstanceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StopDBInstance indicates an expected call of StopDBInstance.
func (mr *MockRdsAPIMockRecorder) StopDBInstance(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopDBInstance", reflect.TypeOf((*MockRdsAPI)(nil).StopDBInstance), varargs...)
}

// MockEcsAPI is a mock of EcsAPI interface.
type MockEcsAPI struct {
	ctrl     *gomock.Controller
	recorder *MockEcsAPIMockRecorder
	isgomock struct{}
}

// MockEcsAPIMockRecorder is the mock recorder for MockEcsAPI.
type MockEcsAPIMockRecorder struct {
	mock *MockEcsAPI
}

// NewMockEcsAPI creates a new mock instance.
func NewMockEcsAPI(ctrl *gomock.Controller) *MockEcsAPI {
	mock := &MockEcsAPI{ctrl: ctrl}
	mock.recorder = &MockEcsAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEcsAPI) EXPECT() *MockEcsAPIMockRecorder {
	return m.recorder
}

// DescribeServices mocks base method.
func (m *MockEcsAPI) DescribeServices(ctx context.Context, in *ecs.DescribeServicesInput, opts ...func(*ecs.Options)) (*ecs.DescribeServicesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeServices", varargs...)
	ret0, _ := ret[0].(*ecs.DescribeServicesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeServices indicates an expected call of DescribeServices.
func (mr *MockEcsAPIMockRecorder) DescribeServices(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeServices", reflect.TypeOf((*MockEcsAPI)(nil).DescribeServices), varargs...)
}

// UpdateService mocks base method.
func (m *MockEcsAPI) UpdateService(ctx context.Context, in *ecs.UpdateServiceInput, opts ...func(*ecs.Options)) (*ecs.UpdateServiceOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateService", varargs...)
	ret0, _ := ret[0].(*ecs.UpdateServiceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateService indicates an expected call of UpdateService.
func (mr *MockEcsAPIMockRecorder) UpdateService(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateService", reflect.TypeOf((*MockEcsAPI)(nil).UpdateService), varargs...)
}

// MockAutoScalingAPI is a mock of AutoScalingAPI interface.
type MockAutoScalingAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAutoScalingAPIMockRecorder
	isgomock struct{}
}

// MockAutoScalingAPIMockRecorder is the mock recorder for MockAutoScalingAPI.
type MockAutoScalingAPIMockRecorder struct {
	mock *MockAutoScalingAPI
}

// NewMockAutoScalingAPI creates a new mock instance.
func NewMockAutoScalingAPI(ctrl *gomock.Controller) *MockAutoScalingAPI {
	mock := &MockAutoScalingAPI{ctrl: ctrl}
	mock.recorder = &MockAutoScalingAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAutoScalingAPI) EXPECT() *MockAutoScalingAPIMockRecorder {
	return m.recorder
}

// DescribeScalableTargets mocks base method.
func (m *MockAutoScalingAPI) DescribeScalableTargets(ctx context.Context, in *applicationautoscaling.DescribeScalableTargetsInput, opts ...func(*applicationautoscaling.Options)) (*applicationautoscaling.DescribeScalableTargetsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeScalableTargets", varargs...)
	ret0, _ := ret[0].(*applicationautoscaling.DescribeScalableTargetsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeScalableTargets indicates an expected call of DescribeScalableTargets.
func (mr *MockAutoScalingAPIMockRecorder) DescribeScalableTargets(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeScalableTargets", reflect.TypeOf((*MockAutoScalingAPI)(nil).DescribeScalableTargets), varargs...)
}

// RegisterScalableTarget mocks base method.
func (m *MockAutoScalingAPI) RegisterScalableTarget(ctx context.Context, in *applicationautoscaling.RegisterScalableTargetInput, opts ...func(*applicationautoscaling.Options)) (*applicationautoscaling.RegisterScalableTargetOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RegisterScalableTarget", varargs...)
	ret0, _ := ret[0].(*applicationautoscaling.RegisterScalableTargetOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterScalableTarget indicates an expected call of RegisterScalableTarget.
func (mr *MockAutoScalingAPIMockRecorder) RegisterScalableTarget(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterScalableTarget", reflect.TypeOf((*MockAutoScalingAPI)(nil).RegisterScalableTarget), varargs...)
}
