// Code generated by MockGen. DO NOT EDIT.
// Source: cheapskate/internal/aws/compute (interfaces: RdsAPI,EcsAPI,AutoScalingAPI,Ec2API)
//
// Generated by this command:
//
//	mockgen -typed -destination mocks/mocks.go -package mocks cheapskate/internal/aws/compute RdsAPI,EcsAPI,AutoScalingAPI,Ec2API
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	applicationautoscaling "github.com/aws/aws-sdk-go-v2/service/applicationautoscaling"
	ec2 "github.com/aws/aws-sdk-go-v2/service/ec2"
	ecs "github.com/aws/aws-sdk-go-v2/service/ecs"
	rds "github.com/aws/aws-sdk-go-v2/service/rds"
	gomock "go.uber.org/mock/gomock"
)

// MockRdsAPI is a mock of RdsAPI interface.
type MockRdsAPI struct {
	ctrl     *gomock.Controller
	recorder *MockRdsAPIMockRecorder
	isgomock struct{}
}

// MockRdsAPIMockRecorder is the mock recorder for MockRdsAPI.
type MockRdsAPIMockRecorder struct {
	mock *MockRdsAPI
}

// NewMockRdsAPI creates a new mock instance.
func NewMockRdsAPI(ctrl *gomock.Controller) *MockRdsAPI {
	mock := &MockRdsAPI{ctrl: ctrl}
	mock.recorder = &MockRdsAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRdsAPI) EXPECT() *MockRdsAPIMockRecorder {
	return m.recorder
}

// DescribeDBClusters mocks base method.
func (m *MockRdsAPI) DescribeDBClusters(ctx context.Context, in *rds.DescribeDBClustersInput, opts ...func(*rds.Options)) (*rds.DescribeDBClustersOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeDBClusters", varargs...)
	ret0, _ := ret[0].(*rds.DescribeDBClustersOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeDBClusters indicates an expected call of DescribeDBClusters.
func (mr *MockRdsAPIMockRecorder) DescribeDBClusters(ctx, in any, opts ...any) *MockRdsAPIDescribeDBClustersCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeDBClusters", reflect.TypeOf((*MockRdsAPI)(nil).DescribeDBClusters), varargs...)
	return &MockRdsAPIDescribeDBClustersCall{Call: call}
}

// MockRdsAPIDescribeDBClustersCall wrap *gomock.Call
type MockRdsAPIDescribeDBClustersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRdsAPIDescribeDBClustersCall) Return(arg0 *rds.DescribeDBClustersOutput, arg1 error) *MockRdsAPIDescribeDBClustersCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRdsAPIDescribeDBClustersCall) Do(f func(context.Context, *rds.DescribeDBClustersInput, ...func(*rds.Options)) (*rds.DescribeDBClustersOutput, error)) *MockRdsAPIDescribeDBClustersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRdsAPIDescribeDBClustersCall) DoAndReturn(f func(context.Context, *rds.DescribeDBClustersInput, ...func(*rds.Options)) (*rds.DescribeDBClustersOutput, error)) *MockRdsAPIDescribeDBClustersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DescribeDBInstances mocks base method.
func (m *MockRdsAPI) DescribeDBInstances(ctx context.Context, in *rds.DescribeDBInstancesInput, opts ...func(*rds.Options)) (*rds.DescribeDBInstancesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeDBInstances", varargs...)
	ret0, _ := ret[0].(*rds.DescribeDBInstancesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeDBInstances indicates an expected call of DescribeDBInstances.
func (mr *MockRdsAPIMockRecorder) DescribeDBInstances(ctx, in any, opts ...any) *MockRdsAPIDescribeDBInstancesCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeDBInstances", reflect.TypeOf((*MockRdsAPI)(nil).DescribeDBInstances), varargs...)
	return &MockRdsAPIDescribeDBInstancesCall{Call: call}
}

// MockRdsAPIDescribeDBInstancesCall wrap *gomock.Call
type MockRdsAPIDescribeDBInstancesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRdsAPIDescribeDBInstancesCall) Return(arg0 *rds.DescribeDBInstancesOutput, arg1 error) *MockRdsAPIDescribeDBInstancesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRdsAPIDescribeDBInstancesCall) Do(f func(context.Context, *rds.DescribeDBInstancesInput, ...func(*rds.Options)) (*rds.DescribeDBInstancesOutput, error)) *MockRdsAPIDescribeDBInstancesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRdsAPIDescribeDBInstancesCall) DoAndReturn(f func(context.Context, *rds.DescribeDBInstancesInput, ...func(*rds.Options)) (*rds.DescribeDBInstancesOutput, error)) *MockRdsAPIDescribeDBInstancesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StartDBCluster mocks base method.
func (m *MockRdsAPI) StartDBCluster(ctx context.Context, in *rds.StartDBClusterInput, opts ...func(*rds.Options)) (*rds.StartDBClusterOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StartDBCluster", varargs...)
	ret0, _ := ret[0].(*rds.StartDBClusterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartDBCluster indicates an expected call of StartDBCluster.
func (mr *MockRdsAPIMockRecorder) StartDBCluster(ctx, in any, opts ...any) *MockRdsAPIStartDBClusterCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartDBCluster", reflect.TypeOf((*MockRdsAPI)(nil).StartDBCluster), varargs...)
	return &MockRdsAPIStartDBClusterCall{Call: call}
}

// MockRdsAPIStartDBClusterCall wrap *gomock.Call
type MockRdsAPIStartDBClusterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRdsAPIStartDBClusterCall) Return(arg0 *rds.StartDBClusterOutput, arg1 error) *MockRdsAPIStartDBClusterCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRdsAPIStartDBClusterCall) Do(f func(context.Context, *rds.StartDBClusterInput, ...func(*rds.Options)) (*rds.StartDBClusterOutput, error)) *MockRdsAPIStartDBClusterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRdsAPIStartDBClusterCall) DoAndReturn(f func(context.Context, *rds.StartDBClusterInput, ...func(*rds.Options)) (*rds.StartDBClusterOutput, error)) *MockRdsAPIStartDBClusterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StartDBInstance mocks base method.
func (m *MockRdsAPI) StartDBInstance(ctx context.Context, in *rds.StartDBInstanceInput, opts ...func(*rds.Options)) (*rds.StartDBInstanceOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StartDBInstance", varargs...)
	ret0, _ := ret[0].(*rds.StartDBInstanceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartDBInstance indicates an expected call of StartDBInstance.
func (mr *MockRdsAPIMockRecorder) StartDBInstance(ctx, in any, opts ...any) *MockRdsAPIStartDBInstanceCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartDBInstance", reflect.TypeOf((*MockRdsAPI)(nil).StartDBInstance), varargs...)
	return &MockRdsAPIStartDBInstanceCall{Call: call}
}

// MockRdsAPIStartDBInstanceCall wrap *gomock.Call
type MockRdsAPIStartDBInstanceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRdsAPIStartDBInstanceCall) Return(arg0 *rds.StartDBInstanceOutput, arg1 error) *MockRdsAPIStartDBInstanceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRdsAPIStartDBInstanceCall) Do(f func(context.Context, *rds.StartDBInstanceInput, ...func(*rds.Options)) (*rds.StartDBInstanceOutput, error)) *MockRdsAPIStartDBInstanceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRdsAPIStartDBInstanceCall) DoAndReturn(f func(context.Context, *rds.StartDBInstanceInput, ...func(*rds.Options)) (*rds.StartDBInstanceOutput, error)) *MockRdsAPIStartDBInstanceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StopDBCluster mocks base method.
func (m *MockRdsAPI) StopDBCluster(ctx context.Context, in *rds.StopDBClusterInput, opts ...func(*rds.Options)) (*rds.StopDBClusterOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StopDBCluster", varargs...)
	ret0, _ := ret[0].(*rds.StopDBClusterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StopDBCluster indicates an expected call of StopDBCluster.
func (mr *MockRdsAPIMockRecorder) StopDBCluster(ctx, in any, opts ...any) *MockRdsAPIStopDBClusterCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopDBCluster", reflect.TypeOf((*MockRdsAPI)(nil).StopDBCluster), varargs...)
	return &MockRdsAPIStopDBClusterCall{Call: call}
}

// MockRdsAPIStopDBClusterCall wrap *gomock.Call
type MockRdsAPIStopDBClusterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRdsAPIStopDBClusterCall) Return(arg0 *rds.StopDBClusterOutput, arg1 error) *MockRdsAPIStopDBClusterCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRdsAPIStopDBClusterCall) Do(f func(context.Context, *rds.StopDBClusterInput, ...func(*rds.Options)) (*rds.StopDBClusterOutput, error)) *MockRdsAPIStopDBClusterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRdsAPIStopDBClusterCall) DoAndReturn(f func(context.Context, *rds.StopDBClusterInput, ...func(*rds.Options)) (*rds.StopDBClusterOutput, error)) *MockRdsAPIStopDBClusterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StopDBInstance mocks base method.
func (m *MockRdsAPI) StopDBInstance(ctx context.Context, in *rds.StopDBInstanceInput, opts ...func(*rds.Options)) (*rds.StopDBInstanceOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StopDBInstance", varargs...)
	ret0, _ := ret[0].(*rds.StopDBInstanceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StopDBInstance indicates an expected call of StopDBInstance.
func (mr *MockRdsAPIMockRecorder) StopDBInstance(ctx, in any, opts ...any) *MockRdsAPIStopDBInstanceCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopDBInstance", reflect.TypeOf((*MockRdsAPI)(nil).StopDBInstance), varargs...)
	return &MockRdsAPIStopDBInstanceCall{Call: call}
}

// MockRdsAPIStopDBInstanceCall wrap *gomock.Call
type MockRdsAPIStopDBInstanceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRdsAPIStopDBInstanceCall) Return(arg0 *rds.StopDBInstanceOutput, arg1 error) *MockRdsAPIStopDBInstanceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRdsAPIStopDBInstanceCall) Do(f func(context.Context, *rds.StopDBInstanceInput, ...func(*rds.Options)) (*rds.StopDBInstanceOutput, error)) *MockRdsAPIStopDBInstanceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRdsAPIStopDBInstanceCall) DoAndReturn(f func(context.Context, *rds.StopDBInstanceInput, ...func(*rds.Options)) (*rds.StopDBInstanceOutput, error)) *MockRdsAPIStopDBInstanceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockEcsAPI is a mock of EcsAPI interface.
type MockEcsAPI struct {
	ctrl     *gomock.Controller
	recorder *MockEcsAPIMockRecorder
	isgomock struct{}
}

// MockEcsAPIMockRecorder is the mock recorder for MockEcsAPI.
type MockEcsAPIMockRecorder struct {
	mock *MockEcsAPI
}

// NewMockEcsAPI creates a new mock instance.
func NewMockEcsAPI(ctrl *gomock.Controller) *MockEcsAPI {
	mock := &MockEcsAPI{ctrl: ctrl}
	mock.recorder = &MockEcsAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEcsAPI) EXPECT() *MockEcsAPIMockRecorder {
	return m.recorder
}

// DescribeServices mocks base method.
func (m *MockEcsAPI) DescribeServices(ctx context.Context, in *ecs.DescribeServicesInput, opts ...func(*ecs.Options)) (*ecs.DescribeServicesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeServices", varargs...)
	ret0, _ := ret[0].(*ecs.DescribeServicesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeServices indicates an expected call of DescribeServices.
func (mr *MockEcsAPIMockRecorder) DescribeServices(ctx, in any, opts ...any) *MockEcsAPIDescribeServicesCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeServices", reflect.TypeOf((*MockEcsAPI)(nil).DescribeServices), varargs...)
	return &MockEcsAPIDescribeServicesCall{Call: call}
}

// MockEcsAPIDescribeServicesCall wrap *gomock.Call
type MockEcsAPIDescribeServicesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEcsAPIDescribeServicesCall) Return(arg0 *ecs.DescribeServicesOutput, arg1 error) *MockEcsAPIDescribeServicesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEcsAPIDescribeServicesCall) Do(f func(context.Context, *ecs.DescribeServicesInput, ...func(*ecs.Options)) (*ecs.DescribeServicesOutput, error)) *MockEcsAPIDescribeServicesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEcsAPIDescribeServicesCall) DoAndReturn(f func(context.Context, *ecs.DescribeServicesInput, ...func(*ecs.Options)) (*ecs.DescribeServicesOutput, error)) *MockEcsAPIDescribeServicesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateService mocks base method.
func (m *MockEcsAPI) UpdateService(ctx context.Context, in *ecs.UpdateServiceInput, opts ...func(*ecs.Options)) (*ecs.UpdateServiceOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateService", varargs...)
	ret0, _ := ret[0].(*ecs.UpdateServiceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateService indicates an expected call of UpdateService.
func (mr *MockEcsAPIMockRecorder) UpdateService(ctx, in any, opts ...any) *MockEcsAPIUpdateServiceCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateService", reflect.TypeOf((*MockEcsAPI)(nil).UpdateService), varargs...)
	return &MockEcsAPIUpdateServiceCall{Call: call}
}

// MockEcsAPIUpdateServiceCall wrap *gomock.Call
type MockEcsAPIUpdateServiceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEcsAPIUpdateServiceCall) Return(arg0 *ecs.UpdateServiceOutput, arg1 error) *MockEcsAPIUpdateServiceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEcsAPIUpdateServiceCall) Do(f func(context.Context, *ecs.UpdateServiceInput, ...func(*ecs.Options)) (*ecs.UpdateServiceOutput, error)) *MockEcsAPIUpdateServiceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEcsAPIUpdateServiceCall) DoAndReturn(f func(context.Context, *ecs.UpdateServiceInput, ...func(*ecs.Options)) (*ecs.UpdateServiceOutput, error)) *MockEcsAPIUpdateServiceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockAutoScalingAPI is a mock of AutoScalingAPI interface.
type MockAutoScalingAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAutoScalingAPIMockRecorder
	isgomock struct{}
}

// MockAutoScalingAPIMockRecorder is the mock recorder for MockAutoScalingAPI.
type MockAutoScalingAPIMockRecorder struct {
	mock *MockAutoScalingAPI
}

// NewMockAutoScalingAPI creates a new mock instance.
func NewMockAutoScalingAPI(ctrl *gomock.Controller) *MockAutoScalingAPI {
	mock := &MockAutoScalingAPI{ctrl: ctrl}
	mock.recorder = &MockAutoScalingAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAutoScalingAPI) EXPECT() *MockAutoScalingAPIMockRecorder {
	return m.recorder
}

// DescribeScalableTargets mocks base method.
func (m *MockAutoScalingAPI) DescribeScalableTargets(ctx context.Context, in *applicationautoscaling.DescribeScalableTargetsInput, opts ...func(*applicationautoscaling.Options)) (*applicationautoscaling.DescribeScalableTargetsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeScalableTargets", varargs...)
	ret0, _ := ret[0].(*applicationautoscaling.DescribeScalableTargetsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeScalableTargets indicates an expected call of DescribeScalableTargets.
func (mr *MockAutoScalingAPIMockRecorder) DescribeScalableTargets(ctx, in any, opts ...any) *MockAutoScalingAPIDescribeScalableTargetsCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeScalableTargets", reflect.TypeOf((*MockAutoScalingAPI)(nil).DescribeScalableTargets), varargs...)
	return &MockAutoScalingAPIDescribeScalableTargetsCall{Call: call}
}

// MockAutoScalingAPIDescribeScalableTargetsCall wrap *gomock.Call
type MockAutoScalingAPIDescribeScalableTargetsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAutoScalingAPIDescribeScalableTargetsCall) Return(arg0 *applicationautoscaling.DescribeScalableTargetsOutput, arg1 error) *MockAutoScalingAPIDescribeScalableTargetsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAutoScalingAPIDescribeScalableTargetsCall) Do(f func(context.Context, *applicationautoscaling.DescribeScalableTargetsInput, ...func(*applicationautoscaling.Options)) (*applicationautoscaling.DescribeScalableTargetsOutput, error)) *MockAutoScalingAPIDescribeScalableTargetsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAutoScalingAPIDescribeScalableTargetsCall) DoAndReturn(f func(context.Context, *applicationautoscaling.DescribeScalableTargetsInput, ...func(*applicationautoscaling.Options)) (*applicationautoscaling.DescribeScalableTargetsOutput, error)) *MockAutoScalingAPIDescribeScalableTargetsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RegisterScalableTarget mocks base method.
func (m *MockAutoScalingAPI) RegisterScalableTarget(ctx context.Context, in *applicationautoscaling.RegisterScalableTargetInput, opts ...func(*applicationautoscaling.Options)) (*applicationautoscaling.RegisterScalableTargetOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RegisterScalableTarget", varargs...)
	ret0, _ := ret[0].(*applicationautoscaling.RegisterScalableTargetOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterScalableTarget indicates an expected call of RegisterScalableTarget.
func (mr *MockAutoScalingAPIMockRecorder) RegisterScalableTarget(ctx, in any, opts ...any) *MockAutoScalingAPIRegisterScalableTargetCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterScalableTarget", reflect.TypeOf((*MockAutoScalingAPI)(nil).RegisterScalableTarget), varargs...)
	return &MockAutoScalingAPIRegisterScalableTargetCall{Call: call}
}

// MockAutoScalingAPIRegisterScalableTargetCall wrap *gomock.Call
type MockAutoScalingAPIRegisterScalableTargetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAutoScalingAPIRegisterScalableTargetCall) Return(arg0 *applicationautoscaling.RegisterScalableTargetOutput, arg1 error) *MockAutoScalingAPIRegisterScalableTargetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAutoScalingAPIRegisterScalableTargetCall) Do(f func(context.Context, *applicationautoscaling.RegisterScalableTargetInput, ...func(*applicationautoscaling.Options)) (*applicationautoscaling.RegisterScalableTargetOutput, error)) *MockAutoScalingAPIRegisterScalableTargetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAutoScalingAPIRegisterScalableTargetCall) DoAndReturn(f func(context.Context, *applicationautoscaling.RegisterScalableTargetInput, ...func(*applicationautoscaling.Options)) (*applicationautoscaling.RegisterScalableTargetOutput, error)) *MockAutoScalingAPIRegisterScalableTargetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockEc2API is a mock of Ec2API interface.
type MockEc2API struct {
	ctrl     *gomock.Controller
	recorder *MockEc2APIMockRecorder
	isgomock struct{}
}

// MockEc2APIMockRecorder is the mock recorder for MockEc2API.
type MockEc2APIMockRecorder struct {
	mock *MockEc2API
}

// NewMockEc2API creates a new mock instance.
func NewMockEc2API(ctrl *gomock.Controller) *MockEc2API {
	mock := &MockEc2API{ctrl: ctrl}
	mock.recorder = &MockEc2APIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEc2API) EXPECT() *MockEc2APIMockRecorder {
	return m.recorder
}

// DescribeInstances mocks base method.
func (m *MockEc2API) DescribeInstances(ctx context.Context, in *ec2.DescribeInstancesInput, opts ...func(*ec2.Options)) (*ec2.DescribeInstancesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeInstances", varargs...)
	ret0, _ := ret[0].(*ec2.DescribeInstancesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeInstances indicates an expected call of DescribeInstances.
func (mr *MockEc2APIMockRecorder) DescribeInstances(ctx, in any, opts ...any) *MockEc2APIDescribeInstancesCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeInstances", reflect.TypeOf((*MockEc2API)(nil).DescribeInstances), varargs...)
	return &MockEc2APIDescribeInstancesCall{Call: call}
}

// MockEc2APIDescribeInstancesCall wrap *gomock.Call
type MockEc2APIDescribeInstancesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEc2APIDescribeInstancesCall) Return(arg0 *ec2.DescribeInstancesOutput, arg1 error) *MockEc2APIDescribeInstancesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEc2APIDescribeInstancesCall) Do(f func(context.Context, *ec2.DescribeInstancesInput, ...func(*ec2.Options)) (*ec2.DescribeInstancesOutput, error)) *MockEc2APIDescribeInstancesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEc2APIDescribeInstancesCall) DoAndReturn(f func(context.Context, *ec2.DescribeInstancesInput, ...func(*ec2.Options)) (*ec2.DescribeInstancesOutput, error)) *MockEc2APIDescribeInstancesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StartInstances mocks base method.
func (m *MockEc2API) StartInstances(ctx context.Context, in *ec2.StartInstancesInput, opts ...func(*ec2.Options)) (*ec2.StartInstancesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StartInstances", varargs...)
	ret0, _ := ret[0].(*ec2.StartInstancesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartInstances indicates an expected call of StartInstances.
func (mr *MockEc2APIMockRecorder) StartInstances(ctx, in any, opts ...any) *MockEc2APIStartInstancesCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartInstances", reflect.TypeOf((*MockEc2API)(nil).StartInstances), varargs...)
	return &MockEc2APIStartInstancesCall{Call: call}
}

// MockEc2APIStartInstancesCall wrap *gomock.Call
type MockEc2APIStartInstancesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEc2APIStartInstancesCall) Return(arg0 *ec2.StartInstancesOutput, arg1 error) *MockEc2APIStartInstancesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEc2APIStartInstancesCall) Do(f func(context.Context, *ec2.StartInstancesInput, ...func(*ec2.Options)) (*ec2.StartInstancesOutput, error)) *MockEc2APIStartInstancesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEc2APIStartInstancesCall) DoAndReturn(f func(context.Context, *ec2.StartInstancesInput, ...func(*ec2.Options)) (*ec2.StartInstancesOutput, error)) *MockEc2APIStartInstancesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StopInstances mocks base method.
func (m *MockEc2API) StopInstances(ctx context.Context, in *ec2.StopInstancesInput, opts ...func(*ec2.Options)) (*ec2.StopInstancesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StopInstances", varargs...)
	ret0, _ := ret[0].(*ec2.StopInstancesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StopInstances indicates an expected call of StopInstances.
func (mr *MockEc2APIMockRecorder) StopInstances(ctx, in any, opts ...any) *MockEc2APIStopInstancesCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopInstances", reflect.TypeOf((*MockEc2API)(nil).StopInstances), varargs...)
	return &MockEc2APIStopInstancesCall{Call: call}
}

// MockEc2APIStopInstancesCall wrap *gomock.Call
type MockEc2APIStopInstancesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEc2APIStopInstancesCall) Return(arg0 *ec2.StopInstancesOutput, arg1 error) *MockEc2APIStopInstancesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEc2APIStopInstancesCall) Do(f func(context.Context, *ec2.StopInstancesInput, ...func(*ec2.Options)) (*ec2.StopInstancesOutput, error)) *MockEc2APIStopInstancesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEc2APIStopInstancesCall) DoAndReturn(f func(context.Context, *ec2.StopInstancesInput, ...func(*ec2.Options)) (*ec2.StopInstancesOutput, error)) *MockEc2APIStopInstancesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
