// Code generated by MockGen. DO NOT EDIT.
// Source: cheapskate/internal/aws/sns (interfaces: API)
//
// Generated by this command:
//
//	mockgen -typed -destination mocks/mocks.go -package mocks cheapskate/internal/aws/sns API
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sns "github.com/aws/aws-sdk-go-v2/service/sns"
	gomock "go.uber.org/mock/gomock"
)

// MockAPI is a mock of API interface.
type MockAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMockRecorder
	isgomock struct{}
}

// MockAPIMockRecorder is the mock recorder for MockAPI.
type MockAPIMockRecorder struct {
	mock *MockAPI
}

// NewMockAPI creates a new mock instance.
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
	mock := &MockAPI{ctrl: ctrl}
	mock.recorder = &MockAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockAPI) Publish(ctx context.Context, in *sns.PublishInput, opts ...func(*sns.Options)) (*sns.PublishOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Publish", varargs...)
	ret0, _ := ret[0].(*sns.PublishOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockAPIMockRecorder) Publish(ctx, in any, opts ...any) *MockAPIPublishCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockAPI)(nil).Publish), varargs...)
	return &MockAPIPublishCall{Call: call}
}

// MockAPIPublishCall wrap *gomock.Call
type MockAPIPublishCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAPIPublishCall) Return(arg0 *sns.PublishOutput, arg1 error) *MockAPIPublishCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAPIPublishCall) Do(f func(context.Context, *sns.PublishInput, ...func(*sns.Options)) (*sns.PublishOutput, error)) *MockAPIPublishCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAPIPublishCall) DoAndReturn(f func(context.Context, *sns.PublishInput, ...func(*sns.Options)) (*sns.PublishOutput, error)) *MockAPIPublishCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
