// Code generated by MockGen. DO NOT EDIT.
// Source: cheapskate/internal/devtools/devseed (interfaces: EcsAPI,TaggingAPI)
//
// Generated by this command:
//
//	mockgen -typed -destination mocks/mocks.go -package mocks cheapskate/internal/devtools/devseed EcsAPI,TaggingAPI
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ecs "github.com/aws/aws-sdk-go-v2/service/ecs"
	resourcegroupstaggingapi "github.com/aws/aws-sdk-go-v2/service/resourcegroupstaggingapi"
	gomock "go.uber.org/mock/gomock"
)

// MockEcsAPI is a mock of EcsAPI interface.
type MockEcsAPI struct {
	ctrl     *gomock.Controller
	recorder *MockEcsAPIMockRecorder
	isgomock struct{}
}

// MockEcsAPIMockRecorder is the mock recorder for MockEcsAPI.
type MockEcsAPIMockRecorder struct {
	mock *MockEcsAPI
}

// NewMockEcsAPI creates a new mock instance.
func NewMockEcsAPI(ctrl *gomock.Controller) *MockEcsAPI {
	mock := &MockEcsAPI{ctrl: ctrl}
	mock.recorder = &MockEcsAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEcsAPI) EXPECT() *MockEcsAPIMockRecorder {
	return m.recorder
}

// CreateCluster mocks base method.
func (m *MockEcsAPI) CreateCluster(ctx context.Context, in *ecs.CreateClusterInput, opts ...func(*ecs.Options)) (*ecs.CreateClusterOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateCluster", varargs...)
	ret0, _ := ret[0].(*ecs.CreateClusterOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCluster indicates an expected call of CreateCluster.
func (mr *MockEcsAPIMockRecorder) CreateCluster(ctx, in any, opts ...any) *MockEcsAPICreateClusterCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCluster", reflect.TypeOf((*MockEcsAPI)(nil).CreateCluster), varargs...)
	return &MockEcsAPICreateClusterCall{Call: call}
}

// MockEcsAPICreateClusterCall wrap *gomock.Call
type MockEcsAPICreateClusterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEcsAPICreateClusterCall) Return(arg0 *ecs.CreateClusterOutput, arg1 error) *MockEcsAPICreateClusterCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEcsAPICreateClusterCall) Do(f func(context.Context, *ecs.CreateClusterInput, ...func(*ecs.Options)) (*ecs.CreateClusterOutput, error)) *MockEcsAPICreateClusterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEcsAPICreateClusterCall) DoAndReturn(f func(context.Context, *ecs.CreateClusterInput, ...func(*ecs.Options)) (*ecs.CreateClusterOutput, error)) *MockEcsAPICreateClusterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateService mocks base method.
func (m *MockEcsAPI) CreateService(ctx context.Context, in *ecs.CreateServiceInput, opts ...func(*ecs.Options)) (*ecs.CreateServiceOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateService", varargs...)
	ret0, _ := ret[0].(*ecs.CreateServiceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateService indicates an expected call of CreateService.
func (mr *MockEcsAPIMockRecorder) CreateService(ctx, in any, opts ...any) *MockEcsAPICreateServiceCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateService", reflect.TypeOf((*MockEcsAPI)(nil).CreateService), varargs...)
	return &MockEcsAPICreateServiceCall{Call: call}
}

// MockEcsAPICreateServiceCall wrap *gomock.Call
type MockEcsAPICreateServiceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEcsAPICreateServiceCall) Return(arg0 *ecs.CreateServiceOutput, arg1 error) *MockEcsAPICreateServiceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEcsAPICreateServiceCall) Do(f func(context.Context, *ecs.CreateServiceInput, ...func(*ecs.Options)) (*ecs.CreateServiceOutput, error)) *MockEcsAPICreateServiceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEcsAPICreateServiceCall) DoAndReturn(f func(context.Context, *ecs.CreateServiceInput, ...func(*ecs.Options)) (*ecs.CreateServiceOutput, error)) *MockEcsAPICreateServiceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DescribeServices mocks base method.
func (m *MockEcsAPI) DescribeServices(ctx context.Context, in *ecs.DescribeServicesInput, opts ...func(*ecs.Options)) (*ecs.DescribeServicesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeServices", varargs...)
	ret0, _ := ret[0].(*ecs.DescribeServicesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeServices indicates an expected call of DescribeServices.
func (mr *MockEcsAPIMockRecorder) DescribeServices(ctx, in any, opts ...any) *MockEcsAPIDescribeServicesCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeServices", reflect.TypeOf((*MockEcsAPI)(nil).DescribeServices), varargs...)
	return &MockEcsAPIDescribeServicesCall{Call: call}
}

// MockEcsAPIDescribeServicesCall wrap *gomock.Call
type MockEcsAPIDescribeServicesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEcsAPIDescribeServicesCall) Return(arg0 *ecs.DescribeServicesOutput, arg1 error) *MockEcsAPIDescribeServicesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEcsAPIDescribeServicesCall) Do(f func(context.Context, *ecs.DescribeServicesInput, ...func(*ecs.Options)) (*ecs.DescribeServicesOutput, error)) *MockEcsAPIDescribeServicesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEcsAPIDescribeServicesCall) DoAndReturn(f func(context.Context, *ecs.DescribeServicesInput, ...func(*ecs.Options)) (*ecs.DescribeServicesOutput, error)) *MockEcsAPIDescribeServicesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DescribeTaskDefinition mocks base method.
func (m *MockEcsAPI) DescribeTaskDefinition(ctx context.Context, in *ecs.DescribeTaskDefinitionInput, opts ...func(*ecs.Options)) (*ecs.DescribeTaskDefinitionOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeTaskDefinition", varargs...)
	ret0, _ := ret[0].(*ecs.DescribeTaskDefinitionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeTaskDefinition indicates an expected call of DescribeTaskDefinition.
func (mr *MockEcsAPIMockRecorder) DescribeTaskDefinition(ctx, in any, opts ...any) *MockEcsAPIDescribeTaskDefinitionCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeTaskDefinition", reflect.TypeOf((*MockEcsAPI)(nil).DescribeTaskDefinition), varargs...)
	return &MockEcsAPIDescribeTaskDefinitionCall{Call: call}
}

// MockEcsAPIDescribeTaskDefinitionCall wrap *gomock.Call
type MockEcsAPIDescribeTaskDefinitionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEcsAPIDescribeTaskDefinitionCall) Return(arg0 *ecs.DescribeTaskDefinitionOutput, arg1 error) *MockEcsAPIDescribeTaskDefinitionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEcsAPIDescribeTaskDefinitionCall) Do(f func(context.Context, *ecs.DescribeTaskDefinitionInput, ...func(*ecs.Options)) (*ecs.DescribeTaskDefinitionOutput, error)) *MockEcsAPIDescribeTaskDefinitionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEcsAPIDescribeTaskDefinitionCall) DoAndReturn(f func(context.Context, *ecs.DescribeTaskDefinitionInput, ...func(*ecs.Options)) (*ecs.DescribeTaskDefinitionOutput, error)) *MockEcsAPIDescribeTaskDefinitionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RegisterTaskDefinition mocks base method.
func (m *MockEcsAPI) RegisterTaskDefinition(ctx context.Context, in *ecs.RegisterTaskDefinitionInput, opts ...func(*ecs.Options)) (*ecs.RegisterTaskDefinitionOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RegisterTaskDefinition", varargs...)
	ret0, _ := ret[0].(*ecs.RegisterTaskDefinitionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterTaskDefinition indicates an expected call of RegisterTaskDefinition.
func (mr *MockEcsAPIMockRecorder) RegisterTaskDefinition(ctx, in any, opts ...any) *MockEcsAPIRegisterTaskDefinitionCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterTaskDefinition", reflect.TypeOf((*MockEcsAPI)(nil).RegisterTaskDefinition), varargs...)
	return &MockEcsAPIRegisterTaskDefinitionCall{Call: call}
}

// MockEcsAPIRegisterTaskDefinitionCall wrap *gomock.Call
type MockEcsAPIRegisterTaskDefinitionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEcsAPIRegisterTaskDefinitionCall) Return(arg0 *ecs.RegisterTaskDefinitionOutput, arg1 error) *MockEcsAPIRegisterTaskDefinitionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEcsAPIRegisterTaskDefinitionCall) Do(f func(context.Context, *ecs.RegisterTaskDefinitionInput, ...func(*ecs.Options)) (*ecs.RegisterTaskDefinitionOutput, error)) *MockEcsAPIRegisterTaskDefinitionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEcsAPIRegisterTaskDefinitionCall) DoAndReturn(f func(context.Context, *ecs.RegisterTaskDefinitionInput, ...func(*ecs.Options)) (*ecs.RegisterTaskDefinitionOutput, error)) *MockEcsAPIRegisterTaskDefinitionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockTaggingAPI is a mock of TaggingAPI interface.
type MockTaggingAPI struct {
	ctrl     *gomock.Controller
	recorder *MockTaggingAPIMockRecorder
	isgomock struct{}
}

// MockTaggingAPIMockRecorder is the mock recorder for MockTaggingAPI.
type MockTaggingAPIMockRecorder struct {
	mock *MockTaggingAPI
}

// NewMockTaggingAPI creates a new mock instance.
func NewMockTaggingAPI(ctrl *gomock.Controller) *MockTaggingAPI {
	mock := &MockTaggingAPI{ctrl: ctrl}
	mock.recorder = &MockTaggingAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaggingAPI) EXPECT() *MockTaggingAPIMockRecorder {
	return m.recorder
}

// TagResources mocks base method.
func (m *MockTaggingAPI) TagResources(ctx context.Context, in *resourcegroupstaggingapi.TagResourcesInput, opts ...func(*resourcegroupstaggingapi.Options)) (*resourcegroupstaggingapi.TagResourcesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TagResources", varargs...)
	ret0, _ := ret[0].(*resourcegroupstaggingapi.TagResourcesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TagResources indicates an expected call of TagResources.
func (mr *MockTaggingAPIMockRecorder) TagResources(ctx, in any, opts ...any) *MockTaggingAPITagResourcesCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagResources", reflect.TypeOf((*MockTaggingAPI)(nil).TagResources), varargs...)
	return &MockTaggingAPITagResourcesCall{Call: call}
}

// MockTaggingAPITagResourcesCall wrap *gomock.Call
type MockTaggingAPITagResourcesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTaggingAPITagResourcesCall) Return(arg0 *resourcegroupstaggingapi.TagResourcesOutput, arg1 error) *MockTaggingAPITagResourcesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTaggingAPITagResourcesCall) Do(f func(context.Context, *resourcegroupstaggingapi.TagResourcesInput, ...func(*resourcegroupstaggingapi.Options)) (*resourcegroupstaggingapi.TagResourcesOutput, error)) *MockTaggingAPITagResourcesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTaggingAPITagResourcesCall) DoAndReturn(f func(context.Context, *resourcegroupstaggingapi.TagResourcesInput, ...func(*resourcegroupstaggingapi.Options)) (*resourcegroupstaggingapi.TagResourcesOutput, error)) *MockTaggingAPITagResourcesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
